import type { ThemeState } from '@/types';

export const DARK_PLUS_PRESET: ThemeState = {
  name: 'Dark+ (default dark)',
  basedOn: 'Dark+',
  workbenchColors: {
    'editor.background': '#1e1e1e',
    'editor.foreground': '#d4d4d4',
    'editor.selectionBackground': '#264f78',
    'editor.lineHighlightBackground': '#2a2d2e',
    'editorCursor.foreground': '#aeafad',
    'editorIndentGuide.background1': '#404040',
    'editorBracketMatch.background': '#0064001a',
    'activityBar.background': '#333333',
    'activityBar.foreground': '#ffffff',
    'activityBar.inactiveForeground': '#ffffff66',
    'sideBar.background': '#252526',
    'sideBar.foreground': '#cccccc',
    'sideBarTitle.foreground': '#bbbbbb',
    'titleBar.activeBackground': '#3c3c3c',
    'titleBar.activeForeground': '#cccccc',
    'tab.activeBackground': '#1e1e1e',
    'tab.inactiveBackground': '#2d2d2d',
    'tab.activeForeground': '#ffffff',
    'tab.inactiveForeground': '#ffffff80',
    'tab.border': '#252526',
    'statusBar.background': '#007acc',
    'statusBar.foreground': '#ffffff',
    'terminal.background': '#1e1e1e',
    'terminal.foreground': '#cccccc',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiRed': '#cd3131',
    'terminal.ansiGreen': '#0dbc79',
    'terminal.ansiYellow': '#e5e510',
    'terminal.ansiBlue': '#2472c8',
    'terminal.ansiMagenta': '#bc3fbc',
    'terminal.ansiCyan': '#11a8cd',
    'terminal.ansiWhite': '#e5e5e5',
    'gitDecoration.addedResourceForeground': '#81b88b',
    'gitDecoration.modifiedResourceForeground': '#e2c08d',
    'gitDecoration.deletedResourceForeground': '#c74e39',
    'gitDecoration.untrackedResourceForeground': '#73c991',
    'minimap.background': '#1e1e1e',
    'minimap.selectionHighlight': '#264f7880',
    'breadcrumb.foreground': '#cccccccc',
    'breadcrumb.activeSelectionForeground': '#e0e0e0',
  },
  tokenColors: [
    { scope: 'comment', settings: { foreground: '#6a9955', fontStyle: 'italic' } },
    { scope: 'string', settings: { foreground: '#ce9178' } },
    { scope: 'keyword', settings: { foreground: '#569cd6' } },
    { scope: 'constant.numeric', settings: { foreground: '#b5cea8' } },
    { scope: 'entity.name.function', settings: { foreground: '#dcdcaa' } },
    { scope: 'entity.name.type', settings: { foreground: '#4ec9b0' } },
    { scope: 'variable', settings: { foreground: '#9cdcfe' } },
    { scope: 'support.type', settings: { foreground: '#4ec9b0' } },
    { scope: 'storage.type', settings: { foreground: '#569cd6' } },
    { scope: 'invalid', settings: { foreground: '#f44747' } },
    { scope: 'entity.name.class', settings: { foreground: '#4ec9b0' } },
    { scope: 'entity.name.interface', settings: { foreground: '#4ec9b0' } },
    { scope: 'variable.parameter', settings: { foreground: '#9cdcfe' } },
    { scope: 'variable.other.property', settings: { foreground: '#9cdcfe' } },
    { scope: 'punctuation', settings: { foreground: '#d4d4d4' } },
    { scope: 'meta.decorator', settings: { foreground: '#dcdcaa' } },
    { scope: 'string.template', settings: { foreground: '#ce9178' } },
    { scope: 'constant.regexp', settings: { foreground: '#d16969' } },
    { scope: 'support.function', settings: { foreground: '#dcdcaa' } },
    { scope: 'keyword.operator', settings: { foreground: '#d4d4d4' } },
  ],
  semanticColors: {
    class: '#4ec9b0',
    enum: '#4ec9b0',
    enumMember: '#4fc1ff',
    function: '#dcdcaa',
    interface: '#4ec9b0',
    method: '#dcdcaa',
    namespace: '#4ec9b0',
    parameter: '#9cdcfe',
    property: '#9cdcfe',
    type: '#4ec9b0',
    typeParameter: '#4ec9b0',
    variable: '#9cdcfe',
    decorator: '#dcdcaa',
  },
};

export const LIGHT_PLUS_PRESET: ThemeState = {
  name: 'Light+ (default light)',
  basedOn: 'Light+',
  workbenchColors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#000000',
    'editor.selectionBackground': '#add6ff',
    'editor.lineHighlightBackground': '#f0f0f0',
    'editorCursor.foreground': '#000000',
    'editorIndentGuide.background1': '#d3d3d3',
    'editorBracketMatch.background': '#0064001a',
    'activityBar.background': '#2c2c2c',
    'activityBar.foreground': '#ffffff',
    'activityBar.inactiveForeground': '#ffffff66',
    'sideBar.background': '#f3f3f3',
    'sideBar.foreground': '#616161',
    'sideBarTitle.foreground': '#6f6f6f',
    'titleBar.activeBackground': '#dddddd',
    'titleBar.activeForeground': '#333333',
    'tab.activeBackground': '#ffffff',
    'tab.inactiveBackground': '#ececec',
    'tab.activeForeground': '#333333',
    'tab.inactiveForeground': '#333333',
    'tab.border': '#f3f3f3',
    'statusBar.background': '#007acc',
    'statusBar.foreground': '#ffffff',
    'terminal.background': '#ffffff',
    'terminal.foreground': '#000000',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiRed': '#cd3131',
    'terminal.ansiGreen': '#00bc00',
    'terminal.ansiYellow': '#949800',
    'terminal.ansiBlue': '#0451a5',
    'terminal.ansiMagenta': '#bc05bc',
    'terminal.ansiCyan': '#0598bc',
    'terminal.ansiWhite': '#555555',
    'gitDecoration.addedResourceForeground': '#587c0c',
    'gitDecoration.modifiedResourceForeground': '#895503',
    'gitDecoration.deletedResourceForeground': '#ad0707',
    'gitDecoration.untrackedResourceForeground': '#007100',
    'minimap.background': '#f3f3f3',
    'minimap.selectionHighlight': '#add6ff80',
    'breadcrumb.foreground': '#615f5f',
    'breadcrumb.activeSelectionForeground': '#4e4e4e',
  },
  tokenColors: [
    { scope: 'comment', settings: { foreground: '#008000', fontStyle: 'italic' } },
    { scope: 'string', settings: { foreground: '#a31515' } },
    { scope: 'keyword', settings: { foreground: '#0000ff' } },
    { scope: 'constant.numeric', settings: { foreground: '#098658' } },
    { scope: 'entity.name.function', settings: { foreground: '#795e26' } },
    { scope: 'entity.name.type', settings: { foreground: '#267f99' } },
    { scope: 'variable', settings: { foreground: '#001080' } },
    { scope: 'support.type', settings: { foreground: '#267f99' } },
    { scope: 'storage.type', settings: { foreground: '#0000ff' } },
    { scope: 'invalid', settings: { foreground: '#cd3131' } },
    { scope: 'entity.name.class', settings: { foreground: '#267f99' } },
    { scope: 'entity.name.interface', settings: { foreground: '#267f99' } },
    { scope: 'variable.parameter', settings: { foreground: '#001080' } },
    { scope: 'variable.other.property', settings: { foreground: '#001080' } },
    { scope: 'punctuation', settings: { foreground: '#000000' } },
    { scope: 'meta.decorator', settings: { foreground: '#795e26' } },
    { scope: 'string.template', settings: { foreground: '#a31515' } },
    { scope: 'constant.regexp', settings: { foreground: '#811f3f' } },
    { scope: 'support.function', settings: { foreground: '#795e26' } },
    { scope: 'keyword.operator', settings: { foreground: '#000000' } },
  ],
  semanticColors: {
    class: '#267f99',
    enum: '#267f99',
    enumMember: '#0070c1',
    function: '#795e26',
    interface: '#267f99',
    method: '#795e26',
    namespace: '#267f99',
    parameter: '#001080',
    property: '#001080',
    type: '#267f99',
    typeParameter: '#267f99',
    variable: '#001080',
    decorator: '#795e26',
  },
};

export const MONOKAI_PRESET: ThemeState = {
  name: 'Monokai',
  basedOn: 'Monokai',
  workbenchColors: {
    'editor.background': '#272822',
    'editor.foreground': '#f8f8f2',
    'editor.selectionBackground': '#49483e',
    'editor.lineHighlightBackground': '#3e3d32',
    'editorCursor.foreground': '#f8f8f0',
    'editorIndentGuide.background1': '#3b3a32',
    'editorBracketMatch.background': '#8b8b8b26',
    'activityBar.background': '#2c2c2b',
    'activityBar.foreground': '#f8f8f2',
    'activityBar.inactiveForeground': '#f8f8f266',
    'sideBar.background': '#1e1f1c',
    'sideBar.foreground': '#bfbfbf',
    'sideBarTitle.foreground': '#f8f8f2',
    'titleBar.activeBackground': '#1c1b1a',
    'titleBar.activeForeground': '#f8f8f2',
    'tab.activeBackground': '#272822',
    'tab.inactiveBackground': '#1e1f1c',
    'tab.activeForeground': '#f8f8f2',
    'tab.inactiveForeground': '#808080',
    'tab.border': '#1e1f1c',
    'statusBar.background': '#75715e',
    'statusBar.foreground': '#f8f8f2',
    'terminal.background': '#272822',
    'terminal.foreground': '#f8f8f2',
    'terminal.ansiBlack': '#272822',
    'terminal.ansiRed': '#f92672',
    'terminal.ansiGreen': '#a6e22e',
    'terminal.ansiYellow': '#f4bf75',
    'terminal.ansiBlue': '#66d9ef',
    'terminal.ansiMagenta': '#ae81ff',
    'terminal.ansiCyan': '#a1efe4',
    'terminal.ansiWhite': '#f8f8f2',
    'gitDecoration.addedResourceForeground': '#a6e22e',
    'gitDecoration.modifiedResourceForeground': '#e6db74',
    'gitDecoration.deletedResourceForeground': '#f92672',
    'gitDecoration.untrackedResourceForeground': '#a6e22e',
    'minimap.background': '#272822',
    'minimap.selectionHighlight': '#49483e80',
    'breadcrumb.foreground': '#bfbfbf',
    'breadcrumb.activeSelectionForeground': '#f8f8f2',
  },
  tokenColors: [
    { scope: 'comment', settings: { foreground: '#75715e', fontStyle: 'italic' } },
    { scope: 'string', settings: { foreground: '#e6db74' } },
    { scope: 'keyword', settings: { foreground: '#f92672' } },
    { scope: 'constant.numeric', settings: { foreground: '#ae81ff' } },
    { scope: 'entity.name.function', settings: { foreground: '#a6e22e' } },
    { scope: 'entity.name.type', settings: { foreground: '#66d9ef', fontStyle: 'italic' } },
    { scope: 'variable', settings: { foreground: '#f8f8f2' } },
    { scope: 'support.type', settings: { foreground: '#66d9ef', fontStyle: 'italic' } },
    { scope: 'storage.type', settings: { foreground: '#f92672' } },
    { scope: 'invalid', settings: { foreground: '#f8f8f0', fontStyle: 'underline' } },
    { scope: 'entity.name.class', settings: { foreground: '#a6e22e' } },
    { scope: 'entity.name.interface', settings: { foreground: '#66d9ef', fontStyle: 'italic' } },
    { scope: 'variable.parameter', settings: { foreground: '#fd971f', fontStyle: 'italic' } },
    { scope: 'variable.other.property', settings: { foreground: '#f8f8f2' } },
    { scope: 'punctuation', settings: { foreground: '#f8f8f2' } },
    { scope: 'meta.decorator', settings: { foreground: '#a6e22e' } },
    { scope: 'string.template', settings: { foreground: '#e6db74' } },
    { scope: 'constant.regexp', settings: { foreground: '#ae81ff' } },
    { scope: 'support.function', settings: { foreground: '#66d9ef' } },
    { scope: 'keyword.operator', settings: { foreground: '#f92672' } },
  ],
  semanticColors: {
    class: '#a6e22e',
    enum: '#66d9ef',
    enumMember: '#ae81ff',
    function: '#a6e22e',
    interface: '#66d9ef',
    method: '#a6e22e',
    namespace: '#66d9ef',
    parameter: '#fd971f',
    property: '#f8f8f2',
    type: '#66d9ef',
    typeParameter: '#66d9ef',
    variable: '#f8f8f2',
    decorator: '#a6e22e',
  },
};

export const GITHUB_DARK_PRESET: ThemeState = {
  name: 'GitHub Dark',
  basedOn: 'GitHub Dark',
  workbenchColors: {
    'editor.background': '#0d1117',
    'editor.foreground': '#e6edf3',
    'editor.selectionBackground': '#388bfd33',
    'editor.lineHighlightBackground': '#161b22',
    'editorCursor.foreground': '#e6edf3',
    'editorIndentGuide.background1': '#21262d',
    'editorBracketMatch.background': '#388bfd40',
    'activityBar.background': '#010409',
    'activityBar.foreground': '#e6edf3',
    'activityBar.inactiveForeground': '#8b949e',
    'sideBar.background': '#010409',
    'sideBar.foreground': '#8b949e',
    'sideBarTitle.foreground': '#8b949e',
    'titleBar.activeBackground': '#010409',
    'titleBar.activeForeground': '#e6edf3',
    'tab.activeBackground': '#0d1117',
    'tab.inactiveBackground': '#010409',
    'tab.activeForeground': '#e6edf3',
    'tab.inactiveForeground': '#8b949e',
    'tab.border': '#21262d',
    'statusBar.background': '#21262d',
    'statusBar.foreground': '#8b949e',
    'terminal.background': '#0d1117',
    'terminal.foreground': '#e6edf3',
    'terminal.ansiBlack': '#484f58',
    'terminal.ansiRed': '#ff7b72',
    'terminal.ansiGreen': '#3fb950',
    'terminal.ansiYellow': '#d29922',
    'terminal.ansiBlue': '#58a6ff',
    'terminal.ansiMagenta': '#bc8cff',
    'terminal.ansiCyan': '#39c5cf',
    'terminal.ansiWhite': '#b1bac4',
    'gitDecoration.addedResourceForeground': '#3fb950',
    'gitDecoration.modifiedResourceForeground': '#d29922',
    'gitDecoration.deletedResourceForeground': '#f85149',
    'gitDecoration.untrackedResourceForeground': '#3fb950',
    'minimap.background': '#0d1117',
    'minimap.selectionHighlight': '#388bfd33',
    'breadcrumb.foreground': '#8b949e',
    'breadcrumb.activeSelectionForeground': '#e6edf3',
  },
  tokenColors: [
    { scope: 'comment', settings: { foreground: '#8b949e', fontStyle: 'italic' } },
    { scope: 'string', settings: { foreground: '#a5d6ff' } },
    { scope: 'keyword', settings: { foreground: '#ff7b72' } },
    { scope: 'constant.numeric', settings: { foreground: '#79c0ff' } },
    { scope: 'entity.name.function', settings: { foreground: '#d2a8ff' } },
    { scope: 'entity.name.type', settings: { foreground: '#ffa657' } },
    { scope: 'variable', settings: { foreground: '#e6edf3' } },
    { scope: 'support.type', settings: { foreground: '#ffa657' } },
    { scope: 'storage.type', settings: { foreground: '#ff7b72' } },
    { scope: 'invalid', settings: { foreground: '#f85149' } },
    { scope: 'entity.name.class', settings: { foreground: '#ffa657' } },
    { scope: 'entity.name.interface', settings: { foreground: '#ffa657' } },
    { scope: 'variable.parameter', settings: { foreground: '#ffa657' } },
    { scope: 'variable.other.property', settings: { foreground: '#e6edf3' } },
    { scope: 'punctuation', settings: { foreground: '#e6edf3' } },
    { scope: 'meta.decorator', settings: { foreground: '#d2a8ff' } },
    { scope: 'string.template', settings: { foreground: '#a5d6ff' } },
    { scope: 'constant.regexp', settings: { foreground: '#7ee787' } },
    { scope: 'support.function', settings: { foreground: '#d2a8ff' } },
    { scope: 'keyword.operator', settings: { foreground: '#ff7b72' } },
  ],
  semanticColors: {
    class: '#ffa657',
    enum: '#ffa657',
    enumMember: '#79c0ff',
    function: '#d2a8ff',
    interface: '#ffa657',
    method: '#d2a8ff',
    namespace: '#ffa657',
    parameter: '#ffa657',
    property: '#e6edf3',
    type: '#ffa657',
    typeParameter: '#ffa657',
    variable: '#e6edf3',
    decorator: '#d2a8ff',
  },
};

export const NEON_RAINBOW_PRESET: ThemeState = {
  name: 'Neon Rainbow',
  basedOn: 'Neon Rainbow',
  workbenchColors: {
    'editor.background': '#0c0c14',
    'editor.foreground': '#e0e0fa',
    'editor.selectionBackground': '#d966ff33',
    'editor.lineHighlightBackground': '#14141f',
    'editorCursor.foreground': '#d966ff',
    'editorIndentGuide.background1': '#2a2a3a',
    'editorBracketMatch.background': '#00f5d440',
    'activityBar.background': '#08080f',
    'activityBar.foreground': '#e0e0fa',
    'activityBar.inactiveForeground': '#6060a0',
    'sideBar.background': '#08080f',
    'sideBar.foreground': '#a0a0d0',
    'sideBarTitle.foreground': '#c8c4ff',
    'titleBar.activeBackground': '#0a0a12',
    'titleBar.activeForeground': '#e0e0fa',
    'tab.activeBackground': '#0c0c14',
    'tab.inactiveBackground': '#08080f',
    'tab.activeForeground': '#e0e0fa',
    'tab.inactiveForeground': '#6060a0',
    'tab.border': '#1a1a2a',
    'statusBar.background': '#1a0030',
    'statusBar.foreground': '#d966ff',
    'terminal.background': '#0c0c14',
    'terminal.foreground': '#e0e0fa',
    'terminal.ansiBlack': '#1a1a2a',
    'terminal.ansiRed': '#ff5e7a',
    'terminal.ansiGreen': '#39ff7a',
    'terminal.ansiYellow': '#f5f050',
    'terminal.ansiBlue': '#4dc9ff',
    'terminal.ansiMagenta': '#d966ff',
    'terminal.ansiCyan': '#00f5d4',
    'terminal.ansiWhite': '#e0e0fa',
    'gitDecoration.addedResourceForeground': '#39ff7a',
    'gitDecoration.modifiedResourceForeground': '#ff9f43',
    'gitDecoration.deletedResourceForeground': '#ff5e7a',
    'gitDecoration.untrackedResourceForeground': '#00f5d4',
    'minimap.background': '#0c0c14',
    'minimap.selectionHighlight': '#d966ff33',
    'breadcrumb.foreground': '#6060a0',
    'breadcrumb.activeSelectionForeground': '#c8c4ff',
  },
  tokenColors: [
    { scope: 'comment', settings: { foreground: '#9966cc', fontStyle: 'italic' } },
    { scope: 'string', settings: { foreground: '#39ff7a' } },
    { scope: 'keyword', settings: { foreground: '#4dc9ff' } },
    { scope: 'constant.numeric', settings: { foreground: '#ff9f43' } },
    { scope: 'entity.name.function', settings: { foreground: '#f5f050' } },
    { scope: 'entity.name.type', settings: { foreground: '#00f5d4' } },
    { scope: 'variable', settings: { foreground: '#c8c4ff' } },
    { scope: 'support.type', settings: { foreground: '#00f5d4' } },
    { scope: 'storage.type', settings: { foreground: '#4dc9ff' } },
    { scope: 'invalid', settings: { foreground: '#ff5e7a', fontStyle: 'underline' } },
    { scope: 'entity.name.class', settings: { foreground: '#00f5d4' } },
    { scope: 'entity.name.interface', settings: { foreground: '#00f5d4' } },
    { scope: 'variable.parameter', settings: { foreground: '#ff9f43', fontStyle: 'italic' } },
    { scope: 'variable.other.property', settings: { foreground: '#c8c4ff' } },
    { scope: 'punctuation', settings: { foreground: '#8080b0' } },
    { scope: 'meta.decorator', settings: { foreground: '#d966ff' } },
    { scope: 'string.template', settings: { foreground: '#39ff7a' } },
    { scope: 'constant.regexp', settings: { foreground: '#ff5e7a' } },
    { scope: 'support.function', settings: { foreground: '#f5f050' } },
    { scope: 'keyword.operator', settings: { foreground: '#4dc9ff' } },
  ],
  semanticColors: {
    class: '#00f5d4',
    enum: '#00f5d4',
    enumMember: '#ff9f43',
    function: '#f5f050',
    interface: '#00f5d4',
    method: '#f5f050',
    namespace: '#00f5d4',
    parameter: '#ff9f43',
    property: '#c8c4ff',
    type: '#00f5d4',
    typeParameter: '#00f5d4',
    variable: '#c8c4ff',
    decorator: '#d966ff',
  },
};

export const PRESETS: ThemeState[] = [
  DARK_PLUS_PRESET,
  LIGHT_PLUS_PRESET,
  MONOKAI_PRESET,
  GITHUB_DARK_PRESET,
  NEON_RAINBOW_PRESET,
];

export const PRESET_NAMES = PRESETS.map((p) => p.basedOn as string);
