version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ../..:/workspaces/chromacode:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/chromacode
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chromacode
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
